# Generated by Django 4.1.6 on 2023-09-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptop'), ('TW', 'Top Wear'), ('BW', 'Bottom Wear'), ('C', 'Cosmatic'), ('O', 'Other'), ('T', 'Tranding')], max_length=2),
        ),
    ]
